### ISSUE TITLE
Remove Ode block type?

### ISSUE THREAD

**Issue by alkino** [BlueBrain/nmodl#1002]
In block types
https://github.com/BlueBrain/nmodl/blob/master/src/codegen/codegen_cpp_visitor.hpp#L49-L86
There is one `Ode`, that seems unused:
https://github.com/BlueBrain/nmodl/blob/master/src/codegen/codegen_cpp_visitor.cpp#L606-L608

Should we remove it totally.
It leads to some line that cannot be covered:
https://github.com/BlueBrain/nmodl/blob/master/src/codegen/codegen_cpp_visitor.cpp#L617-L619
and follow.

**Comment by pramodk** [comment]
> Should we remove it totally.

ODEs are represented by other block types. So can't think of immediate reason. OK to remove IMO.
