### ISSUE TITLE
Descripancy in calculation of Newton solver solution

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/nmodl#1024]
In the DERVIATIVE block there are the derivatives (`dvar`) which we translate to C++ code.
Then those need to be used to update the states like:
```
var = var + dt * dvar
```
In NMODL we do all these in one step as you can see.
In mod2c/neuron we first calculate all the `dvar` first in `state ::operator()` and then we apply them to the `var` in `newton_solver.` 
Since all this are done in a single step in `nmodl` for all the variables we might end up with the following:
```
var1 = var1 + dt * dvar1()
var2 = var2 + dt * dvar2(var1)
```
The problem exists if `dvar2` depends on `var1` and gets computed after var1 so it has the new value
In mod2c/neuron we calculate this like that:
```
Dvar1 = dvar1()
Dvar2 = dvar2(var1)
var1 = var1 + dt * Dvar1
var2 = var2 + dt * Dvar2
```
The derivatives (`dvar1()`/`dvar2()`) in both `mod2c` and `nmodl` are calculated in the same way though

**Comment by olupton** [comment]
Can you add some more background on where was this issue identified?

**Comment by iomaganaris** [comment]
The issue was identified with the `hippocampus` BBP circuit.
If we install `neuron+nmodl` with spack and try to launch the `blueconfigs` CI the corresponding test will fail.
