### ISSUE TITLE
Relicense NMODL from LGPL to Apache-2.0

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#1047]
### Summary

We would like to change the license for NMODL from the current LGPL to [Apache License, version 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)).

### Why Apache-2.0?

The motivation for this license change is to maximize the accessibility of NMODL and integration into open-source software without doubts around license compatibility (e.g. integration at the source level in BSD/Apache/MIT projects). By being more open/flexible with the license, we believe it will be helpful in the longer term.

### What do contributors need to do?

We would like to ask permission from all **external/non-bbp contributors** to change the license to Apache 2.0. Good news: with all current contributions to the master, I don't see any external/non-BBP member :).

As we are at this stage, maybe I can ask @georgemitenkov to provide the approval for all of his LLVM-related work.

If you agree with the proposed license change, we would like to request you to copy the message below, fill in the blanks and paste it into this issue.

```
My name is _________________________, and I am a contributor to NMODL
with GitHub username _________________________.

I consent to change the current license contained in the License file at
https://github.com/BlueBrain/nmodl/blob/master/LICENSE from the
LGPL license to the Apache License 2.0 with respect to all of my
contributions.
```

If you have any questions or concerns, please ask here or send an email to me/us.

Thanks!

**Comment by georgemitenkov** [comment]
My name is George Mitenkov, and I am a contributor to NMODL
with GitHub username `georgemitenkov`.

I consent to change the current license contained in the License file at
https://github.com/BlueBrain/nmodl/blob/master/LICENSE from the
LGPL license to the Apache License 2.0 with respect to all of my
contributions.

**Comment by pramodk** [comment]
@nrnhines: I will take the opportunity to ask you the same here: some of the lexer and parser files are **_derived_** from the NEURON's nocmodl implementation (e.g. [src/lexer/nmodl.ll](https://github.com/BlueBrain/nmodl/blob/ce25655088cb082b5c0c9dc9cc9a423739799806/src/lexer/nmodl.ll#L4), [src/parser/nmodl.yy](https://github.com/BlueBrain/nmodl/blob/ce25655088cb082b5c0c9dc9cc9a423739799806/src/parser/nmodl.yy#L4), [diffeq.yy](https://github.com/BlueBrain/nmodl/blob/ce25655088cb082b5c0c9dc9cc9a423739799806/src/parser/diffeq.yy#L4)). I guess you would agree to relicense these files under Apache2 license in NMODL repo?

**Comment by nrnhines** [comment]
I have no issue with the license change.
