### ISSUE TITLE
Validation of traub model with NMODL

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#108]
Repository of traub model is : 

```
git checkout https://github.com/pramodk/nrntraub  -b icei
```

**Comment by iomaganaris** [comment]
@pramodk This could be closed since the validation was done with the right results if I remember correctly?

**Comment by pramodk** [comment]
This needs to be re-done considering bug fixes we have done. The [notes/instructions](https://github.com/pramodk/nrntraub/blob/icei/notes) are bit outdated. (Without trying myself), steps should be:

```console

# install neuron
1. Install NEURON + CoreNEURON + MOD2C with GPU support enabled
2. Install NEURON + CoreNEURON + NMODL with GPU support enabled
3. Install NEURON + CoreNEURON + NMODL with GPU support enabled and sympy solver (optional, ask Ioannis about this)
 
# prepare mod file directory 
mkdir coredat
mkdir modcore
cp mod/*.mod modcore
rm modcore/ri.mod

# for a given installation of NEURON, compile mod files
nrnivmodl -coreneuron modcore

# run from repository

# run neuron first
export HOC_LIBRARY_PATH=`pwd`/hoc
./x86/special -c mytstop=100 run.hoc

# run coreneuron on cpu or gpu
./x86/special -c mytstop=100 -c coreneuron=1 run.hoc

# compare spike output
sh compare.sh out1.dat out0.dat | more
```

IIRC, run.hoc needs to be updated in order to lunch CoreNEURON. See the implementation [here](https://github.com/neuronsimulator/testcorenrn/blob/7b781b3a7ac1e0b785f897e4db5c3bf84c5127d2/common.hoc#L34).
