### ISSUE TITLE
Duplication of SOLVE leads to error or hang

### ISSUE THREAD

**Issue by thorstenhater** [BlueBrain/nmodl#1092]
Hi,

as the title says, the following file leads to a hang (with `METHOD cnexp` commented) out
or an error (with `METHOD cnexp` active) although it seems perfectly well defined:
```
NEURON {
    SUFFIX test
    NONSPECIFIC_CURRENT i
}

STATE { x y }

INITIAL {
  x = 42
  y = 23
}

BREAKPOINT {
    SOLVE dX : METHOD cnexp
    SOLVE dY : METHOD cnexp

    i = x*y
}

DERIVATIVE dX { x' = -0.1*x }

DERIVATIVE dY { y' = -0.1*y }
```

Tested w/ Neuron 8.2.2

**Comment by ramcdougal** [comment]
Is this a thing that NEURON/nmodl should support? Or should it raise a compilation error?

**Comment by thorstenhater** [comment]
At least it shouldn't hang indefinitely and throw an error. If you want to spent the extra effort, supporting this 
shouldn't be too hard and even might yield some performance  improvements. It's not used in the wild but occurred
to me while coming up with more corner cases for Arbor's NMODL handling.

**Comment by 1uc** [comment]
Thank you for reporting the issue. When using the current master of `nrn` (with the associated version of nmodl), then I get the following:
```
$ nrnivmodl -coreneuron                                                                                       [17:06:09]
/home/lucg/git/bbp/nmodl_benchmark/issue-1092
cfiles =
Mod files: "leonhard.mod"

MODOBJS= ./leonhard.o
[INFO] Running: make -j4 -f ${NRN_DIR}/build-release/install/share/coreneuron/nrnivmodl_core_makefile ROOT=${NRN_DIR}/build-release/install MODS_PATH=x86_64/corenrn/mod2c BUILD_TYPE=SHARED NRN_PRCELLSTATE=0
make: xcrun: No such file or directory
Default NMODL flags: 
x86_64/corenrn/mod2c/leonhard.cpp: In function ‘double coreneuron::nrn_current_leonhard(int, int, leonhard_Instance*, double*, const Datum*, ThreadDatum*, NrnThread*, double)’:
x86_64/corenrn/mod2c/leonhard.cpp:260:9: error: ‘i’ was not declared in this scope; did you mean ‘id’?
  260 |         i = inst->x[id] * inst->y[id];
      |         ^
      |         id
make: *** [${NRN_DIR}/build-release/install/share/coreneuron/nrnivmodl_core_makefile:184: x86_64/corenrn/build/leonhard.o] Error 1
```
(Which technically counts as "doesn't compile". Obviously for the wrong reasons. The rest of the file look promising, i.e. like it's doing the right thing for these two very simple ODEs.)

```
$ nrnivmodl
cfiles =
Mod files: "leonhard.mod"

Creating 'x86_64' directory for .o files.

MODOBJS= ./leonhard.o
 -> Compiling mod_func.cpp
 -> NMODL ../leonhard.mod
Translating leonhard.mod into ${PWD}/x86_64/leonhard.cpp
syntax error:
 Illegal SOLVE statement:
 Error: Illegal block at line 15 in file leonhard.mod
    SOLVE dY METHOD cnexp
                         ^
make: *** [makemod2c_inc:3: leonhard.cpp] Error 1
make: *** Waiting for unfinished jobs....
```
where line 15 is the second `SOLVE` block. To me this suggests that the "spec", i.e. NRN, says it's not allowed.

@thorstenhater When you say performance benefits, what are you thinking of? The fact that it's two decoupled ODE and therefore, we don't need to solve a 2x2 system of ODEs? If yes, that's something one could teach NMODL how to detect. There's no need for the user to help the codegenerator in that regard.

**Comment by thorstenhater** [comment]
Yes, I was thinking about that particular case when mentioning performance. As noted above, this is not a request,
just something I came up with while investigating corner cases in our (=Arbor's) NMODL translation.

**Comment by pramodk** [comment]
> To me this suggests that the "spec", i.e. NRN, says it's not allowed.

@alkino: you have the `SemanticAnalysisVisitor` where such check for finding > SOLVE statements can go I think.

**Comment by pramodk** [comment]
@nrnhines: Just want to clarify the multiple `SOLVE` statements issue discussed in this ticket: 

After looking into the [ModelDB MOD file orn.mod](https://modeldb.science/240116?tab=2&file=modeldb-bulb3d/sim/orn.mod), I see that there can be multiple SOLVE statements and NEURON accepts it. There is an issue when there is more than one DERIVATIVE block.

So for now, on coreneuron+nmodl side, we will throw an error when there are multiple DERIVATIVE blocks. Currently, NEURON hangs with the above example in the description. In a separate PR we can handle this on neuron side (i.e. throw an error than deadlock)

**Comment by nrnhines** [comment]
@pramodk I've looked at the orn.mod file and believe the only reason for the SOLVE of the PROCEDURE block is so that it is executed once per time step (instead of twice for the fixed step method). I think the conceptual goal here is to randomly change the ge_1 variable at the beginning of the time step.  This can be done better in a ```BEFORE STEP``` block.

**Comment by pramodk** [comment]
thank you @nrnhines for looking into it. My intention is not necessarily to fix that MOD file. It's just that we thought more than 1 SOLVE statement was not used and hence shouldn't be supported. But with the olfactory-bulb model, we saw that this specific pattern is used.
