### ISSUE TITLE
Reviewing yaml language parsing and ast generation python code

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#11]
The YAML [specification](../blob/master/src/language/nmodl.yaml) of NMODL language is parsed using the python code in [language/code_generator.py](../blob/master/src/language/code_generator.py). The goal of this ticket is to : 

* review and improve current implementation  :
  * parser.py
  * code_generator.py
  * nodes.py

I wrote the initial implementation so not sure if it is pythonic :)

@ferdonline  : this is not urgent, whenever you feel like reviewing / lightweight improving some part of the code.

**Comment by alkino** [comment]
I think it can be closed. The code have been reviewed right now, I hope :p

**Comment by tristan0x** [comment]
I agree with @alkino , this part of the code is clean enough.
@ferdonline  ?

**Comment by pramodk** [comment]
It was improved quite by @tristan0x and others (including @matz-e IIRC).
