### ISSUE TITLE
Remove `-DNMODL_CLANG_FORMAT`.

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/nmodl#1158]
There's documentation that suggest that `-DNMODL_FORMATTING` activates automatic formatting. It's documented here:
https://github.com/BlueBrain/nmodl/blob/ec0db70590e72e89ae56ae5e2cd992abb3b40f3f/CONTRIBUTING.rst?plain=1#L155-L161

but neither flag seems to work for me and the targets don't seem to exist. I've been using:
```
$ cmake/hpc-coding-conventions/bin/format
```
in the past which works without issues. I would suggest deleting the related CMake code.

**Comment by alkino** [comment]
Of course, this was old system.

**Comment by 1uc** [comment]
It formats code generated by JINA, not the output of NMODL. Apparently, this was useful.
