### ISSUE TITLE
Issue with solver: "Newton solver did not converge"

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#1194]
### Overview

Thanks to @vignan21 for providing the attached simplified, single-cell model. When running with CoreNEURON, we get the following error:

```console
./x86_64/special -python run.py
NEURON -- VERSION 8.2.3-6-gde9333d0f+ jelic/backport_unified_setup (de9333d0f+) 2024-01-11
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2022
See http://neuron.yale.edu/neuron/credits

Additional mechanisms from files
 "mods//bk_ch.mod" "mods//ca_ch.mod" "mods//cal2.mod" "mods//cal_ch.mod" "mods//cap_ch.mod" "mods//hcn12_ch.mod" "mods//kcnq_ch.mod" "mods//kir23_ch.mod" "mods//kir2_ch.mod" "mods//kv2_ch.mod" "mods//kv4_ch.mod" "mods//na2_ch.mod" "mods//na_ch.mod" "mods//sk_ms.mod"
h.Cell_0("morphologies")

 Duke, Yale, and the BlueBrain Project -- Copyright 1984-2020
 Version : 9.0.0 df622969d (2024-03-01 21:57:54 +0100)

....

 Memory (MBs) :  After mk_spikevec_buffer : Max 67.7578, Min 67.7578, Avg 67.7578
 Memory (MBs) :     After nrn_finitialize : Max 68.2734, Min 68.2734, Avg 68.2734

special: x86_64/corenrn/mod2c/ca_ch.cpp:540: void coreneuron::nrn_state_ca_ch(coreneuron::NrnThread*, coreneuron::Memb_list*, int): 
Assertion `false && "Newton solver did not converge!"' failed.
Aborted
```

This error doesn't happen when we run the same model with NEURON.

### How to Run 

* Download attached zip
* Compile mod files `nrnivmodl -coreneuron mods/`
* Run with NEURON or CoreNEURON: toggle line # 9: `coreneuron.enable = False`

### Todos

* Understand what's causing the error
* Implement necessary changes in the solvers to avoid this type of errors

**Comment by 1uc** [comment]
@pramodk I don't see anything attached.

**Comment by pramodk** [comment]
Sorry, forgot to attach the model: [test_nmodl_solver.tgz](https://github.com/BlueBrain/nmodl/files/14482642/test_nmodl_solver.tgz)

**Comment by 1uc** [comment]
The first issue is that NMODL fails for KINETIC blocks that express some of the reaction equations in a `FROM ... TO ...` loop.

This can be worked around by either manually unrolling the loop; or by instructing NMODL to do the same:
```
nmodl MOD_FILE passes --const-folding --unroll --const-folding
```

**Comment by 1uc** [comment]
The second (potential issue) is the model contains:
```
 ~ca[0] + pump <-> pumpca      ((1.e-11)*k1*area, (1.e7)  *k2*area)
```
this results in a system of non-linear equations, that contain a term:
```
f[0] = ... + 10000000.0 * x[13] * area * dt * k2 + ...
```
and the corresponding derivative:
```
j[0, 13] = 10000000.0 * area * dt * k2;  // approx. 1e17
```
all other entries are either roughly 1, 1e5 (lower left corner) or zero.

**Comment by 1uc** [comment]
Unfortunately,
```
nmodl MOD_FILE passes --const-folding --unroll --const-folding
```
only works for models with `COMPARTMENT` blocks.

**Comment by 1uc** [comment]
Let's summarize what's happening. We start from a MOD file containing: 
```
DEFINE NANN  4

ASSIGNED {
    cai         (mM)
    ipump       (mA/cm2)
    volume[NANN]
}

STATE {
    ca[NANN]        (mM) <1.e-5> : ca[0] is equivalent to cai
}

BREAKPOINT {
    SOLVE state METHOD sparse
    ica = ipump
}

KINETIC state {
    COMPARTMENT i, volume[i] {ca}
    COMPARTMENT 321.0 {cao}

    ~ ca[0] << (1.2)

    FROM i=0 TO NANN-2 {
        ~ ca[i] <-> ca[i+1]     (0.9, 0.8)
    }

    ~ ca[3] <-> cao             (0.5, 0.4)

    ipump = (f_flux-b_flux)/area
    cai = ca[0]
}
```
When transforming this there's a few failures. First off:
```
    FROM i=0 TO NANN-2 {
        ~ ca[i] <-> ca[i+1]     (0.9, 0.8)
    }
```
does not yield any ODEs in the intermediate transformations. Instead it produces:
```
DERIVATIVE state {
    FROM i = 0 TO NANN-2 {
    }
    ipump = (0.5*ca[3]-0.4*cao)/area
    cai = ca[0]
    ca'[0] = (1.2)
    ca'[3] = (-1*(0.5*ca[3]-0.4*cao))
}
```
This can be "fixed" by performing const-folding followed by unrolling. This generates: 
```
KINETIC state {
    COMPARTMENT i, volume[i] {ca}
    COMPARTMENT 321.0 {cao}
    ~ ca[0] << (1.2)
    {
        ~ ca[0] <-> ca[1] (0.9, 0.8)
        ~ ca[1] <-> ca[2] (0.9, 0.8)
        ~ ca[2] <-> ca[3] (0.9, 0.8)
    }
    ~ ca[3] <-> cao (0.5, 0.4)
    ipump = (f_flux-b_flux)/area
    cai = ca[0]
}
```
Then next stage converts reaction equation into a system of ODEs:
```
DERIVATIVE state {
    {
    }
    ipump = (0.5*ca[3]-0.4*cao)/area
    cai = ca[0]
    ca'[0] = (1.2)+(-1*(0.9*ca[0]-0.8*ca[1]))
    ca'[1] = (1*(0.9*ca[0]-0.8*ca[1]))+(-1*(0.9*ca[1]-0.8*ca[2]))
    ca'[2] = (1*(0.9*ca[1]-0.8*ca[2]))+(-1*(0.9*ca[2]-0.8*ca[3]))
    ca'[3] = (1*(0.9*ca[2]-0.8*ca[3]))+(-1*(0.5*ca[3]-0.4*cao))
}
```
Which is wrong, because we should be dividing by the size of each compartment:
```
    ca'[0] = ((1.2)+(-1*(0.9*ca[0]-0.8*ca[1]))) / volume[0]
    ca'[1] = ((1*(0.9*ca[0]-0.8*ca[1]))+(-1*(0.9*ca[1]-0.8*ca[2]))) / volume[1]
    ca'[2] = ((1*(0.9*ca[1]-0.8*ca[2]))+(-1*(0.9*ca[2]-0.8*ca[3]))) / volume[2]
    ca'[3] = ((1*(0.9*ca[2]-0.8*ca[3]))+(-1*(0.5*ca[3]-0.4*cao))) / volume[3]
```

**Comment by 1uc** [comment]
First we need to fix the issue with the `COMPARTMENT` (because we can temporarily avoid the `FROM ... TO ... ` problem. Currently, compartments work by computing the volume when the statement is visited and storing it for later retrieval.

This can't work for indexed `COMPARTMENT` blocks, because we don't know for how many variables we need to generate and store volumes.

We can switch API to something like:
```
double volume = compartment_factor(variable /* "ca[0]" */);
```
the function can then check any the regular compartments and see if any match. If none match it can check if any of the indexed compartments match; and then compute and return the volume (resolving any indexes used in the volume expression).

**Comment by 1uc** [comment]
Required fixes:
* https://github.com/BlueBrain/nmodl/pull/1209
* https://github.com/BlueBrain/nmodl/pull/1214
* https://github.com/BlueBrain/nmodl/pull/1232
* https://github.com/BlueBrain/nmodl/pull/1233
* https://github.com/neuronsimulator/nrn/pull/2779
