### ISSUE TITLE
Issue with ION ordering in code generation

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#150]
Consider below example from reduced_dentate model (#107), 

```
NEURON {
    SUFFIX ccanl
        USEION nca READ ncai, inca, enca WRITE enca, ncai VALENCE 2
        USEION lca READ lcai, ilca, elca WRITE elca, lcai VALENCE 2
        USEION tca READ tcai, itca, etca WRITE etca, tcai VALENCE 2
        RANGE caiinf, catau, cai, ncai, lcai,tcai, eca, elca, enca, etca
}

UNITS {
        (mV) = (millivolt)
    (molar) = (1/liter)
    (mM) = (milli/liter)
    (mA) = (milliamp)
    FARADAY = 96520 (coul)
    R = 8.3134  (joule/degC)
}

:INDEPENDENT {t FROM 0 TO 100 WITH 100 (ms)}

PARAMETER {
    depth = 200 (nm)    : assume volume = area*depth
    catau = 9 (ms)
    caiinf = 50.e-6 (mM)
    cao = 2 (mM)
}

ASSIGNED {
        celsius (degC)
    ica (mA/cm2)
    inca (mA/cm2)
    ilca (mA/cm2)
    itca (mA/cm2)
    cai (mM)

    enca (mV)
    elca (mV)
    etca (mV)
    eca (mV)
}

STATE {
    ncai (mM)
    lcai (mM)
    tcai (mM)
}
```

Here is comparison of data structures order from mod2c and nmodl : 

![ccanl](https://user-images.githubusercontent.com/666852/56515158-87f38180-6537-11e9-92aa-aa68d811340d.png)

Issues : 

* order of ion variables is wrong
* same ion variable can be used as read as well as write : in this case the variable shouldn't be declared as const

This issue was also seen while testing #148.

**Comment by pramodk** [comment]
@iomaganaris : see for long I have been postponing this! :disappointed:

**Comment by iomaganaris** [comment]
We figured out that there is an issue with the ordering of the `ion` variable indexes on https://github.com/pramodk/reduced_dentate/blob/master/mechanisms/LcaMig.mod. Especially the issue is with `cao` and `cai` variables indexes. To fix this issue we changed a bit the mod file to: https://github.com/pramodk/reduced_dentate/blob/master/mechanisms/LcaMig.mod

**Comment by pramodk** [comment]
Let's look at the examples of `TLcaMig.mod` in the reduced_dentate model:

```python
$ cat mechanisms/LcaMig.mod
TITLE l-calcium channel
: l-type calcium channel


UNITS {
	(mA) = (milliamp)
	(mV) = (millivolt)
	(molar) = (1/liter)
	(mM) = (millimolar)
	FARADAY = 96520 (coul)
	R = 8.3134 (joule/degC)
	KTOMV = .0853 (mV/degC)
}

PARAMETER {
	glcabar		 (mho/cm2)
	ki=.001 (mM)
	cao (mM)
        tfa=1
}


NEURON {
	SUFFIX lca
	USEION lca READ elca WRITE ilca VALENCE 2
	USEION ca READ cai, cao VALENCE 2
        RANGE glcabar, cai, ilca, elca
        :GLOBAL minf,matu
	RANGE minf,matu
}
```
In the above example, `cao` is defined first in the PARAMETER block and hence appear ahead of `cai` in the NMODL symbol table. 

In case of NMODL, when C++ code is printed, its getting read ion variable based on symbol table: https://github.com/BlueBrain/nmodl/blob/189e35c81201b49d5cfc99256a19b7e78364a3e8/src/codegen/codegen_helper_visitor.cpp#L69

```cpp
    auto ion_vars = psymtab->get_variables_with_properties(NmodlType::useion);
    /// read variables from all ions
    auto read_ion_vars = psymtab->get_variables_with_properties(NmodlType::read_ion_var);
    /// write variables from all ions
    auto write_ion_vars = psymtab->get_variables_with_properties(NmodlType::write_ion_var);

    /**
     * Check if given variable belongs to given ion.
     * For example, eca belongs to ca ion, nai belongs to na ion.
     * We just check if we exclude first/last char, if that is ion name.
     */
    auto ion_variable = [](const std::string& var, const std::string& ion) -> bool {
        auto len = var.size() - 1;
        return (var.substr(1, len) == ion || var.substr(0, len) == ion);
    };

    /// iterate over all ion types and construct the Ion objects
    for (auto& ion_var: ion_vars) {
        auto ion_name = ion_var->get_name();
        Ion ion(ion_name);
        for (auto& read_var: read_ion_vars) {
            auto var = read_var->get_name();
            if (ion_variable(var, ion_name)) {
                ion.reads.push_back(var);
            }
```

In case of MOD2C, the order of read ion variables is based on the order of `USEION` statements in the MOD file (i.e. PARAMETER block doesn't influence anything!):

https://github.com/BlueBrain/mod2c/blob/42bb3c3d6fa70e8f4ad89ab448910c006ad30359/src/mod2c_core/nocpout.c#L1998
https://github.com/BlueBrain/mod2c/blob/42bb3c3d6fa70e8f4ad89ab448910c006ad30359/src/mod2c_core/nocpout.c#L2363
And hence the issue!

So, I think the solution is, NMODL should give up the ordering based on symbol table and use USEION statements from the AST to get variable order. This will resolve the issue for LcaMig.mod. The issue mentioned for ccanl.mod is already resolved.

I will work on this tomorrow. 

> NOTE: simple solution of moving PARAMETER block after NEURON block will solve the issue. Or, doing other way around will introduce bug in any model!
