### ISSUE TITLE
pip install - sphinx required version conflict

### ISSUE THREAD

**Issue by lkeegan** [BlueBrain/nmodl#163]
pip install gives me a version conflict:
breathe requires sphinx>=2, but in setup.py we require sphinx<2.

If I remove the `<2` bit from the `sphinx<2` in this line the install works:
https://github.com/BlueBrain/nmodl/blob/c32eebd579e9a830cf3325b8399201d09a7a818e/setup.py#L152

(should it maybe be `>=2`?)

**Comment by tapaswenipathak** [comment]
hello folks, I can PR a fix for this, is this still open?

**Comment by pramodk** [comment]
we are not using exhale anymore. latest setup.py is already updated.
