### ISSUE TITLE
Directly construct LookupVisitors instead of constructing & assigning

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/nmodl#171]
As @tristan0x pointed out we should for instance write

```
auto lv = AstLookupVisitor(ast::AstNodeType::FUNCTION_CALL);
```
as
```
 AstLookupVisitor lv(ast::AstNodeType::FUNCTION_CALL);
```

That's an easy cleanup that should be done throughout the code.

**Comment by tapaswenipathak** [comment]
hi @ohm314, can I work on this?

**Comment by pramodk** [comment]
@tapaswenipathak  : this is easy and straightforward to start with. please go ahead!

**Comment by cattabiani** [comment]
@tapaswenipathak are you still working on this? I may take over this to familiarize with the code
