### ISSUE TITLE
DEFINE keyword issues

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/nmodl#214]
@nrnhines reported issues while trying to translate [`cabpump.mod`](https://github.com/neuronsimulator/nrn/blob/master/share/demo/release/cabpump.mod) which include the following line:
```
DEFINE NANN  10
```
`NANN` is interpreted as `NAN` and when changed to `NANNULI` the `DEFINE` was being ignored.
The original file and a patched one that resolves some of the issues of this `mod file` can be found in [cabpump.zip](https://github.com/BlueBrain/nmodl/files/3281214/cabpump.zip).

**Comment by alkino** [comment]
This problem seems solve. I translate the above file and everything seems fine.

**Comment by iomaganaris** [comment]
Cool. This can be closed then
