### ISSUE TITLE
Install using pip: config.py not generated

### ISSUE THREAD

**Issue by lkoelman** [BlueBrain/nmodl#224]
I installed successfully using pip following the installation instructions. However when attempting to run the example I get an error (pasted below), which seems to be related to the fact that `config.py.in` in `nmodl/nmodl` is not succesfully generated and copied during installation using `pip install --user .`. I verified that there was no config.py present in `~/.local/lib/python3.7/site-packages/nmodl/`.

Operating system is Ubuntu 18 and Python is 3.7 installed using anaconda.

```
<ipython-input-1-16685df1c4a8> in <module>
----> 1 import nmodl.dsl as nmodl

~/.local/lib/python3.7/site-packages/nmodl/dsl.py in <module>
      1 from ._nmodl import *
----> 2 from .config import *
      3 
      4 
      5 def example_dir():

ModuleNotFoundError: No module named 'nmodl.config'

```

**Comment by ohm314** [comment]
Hi @lkoelman 

Actually, I’ve noticed this issue a couple days ago myself. Not entirely sure yet what’s going on, but I’ll try to follow up in the next days. As a workaround, you can copy and rename the config.py.in yourself and set the installation paths inside the file.

**Comment by lkoelman** [comment]
Great, thanks for the update. Workaround confirmed to work .

**Comment by pramodk** [comment]
@lkoelman : latest master should have fixed the issue. Let us know if you see any other issue.
