### ISSUE TITLE
Regression in ispc code generation where used functions are emitted into c++ code

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/nmodl#237]
Functions that are called in ispc should be generated in ispc, otherwise they cannot be found. For example:

```bash
nmodl hh.mod host --ispc
```

will generate `hh.ispc` and `hh.cpp` . In `rates_hh` we call the function `vtrap_hh`. This function was, however, generated in `hh.cpp` in C++ code and cannot be found when compiling `hh.ispc`.

### Temporary workaround:

Generate code with the `--inline` pass. e.g.

```bash
nmodl hh.mod host --ispc passes --inline
```

**Comment by alkino** [comment]
ISPC backend have been removed in #963
