### ISSUE TITLE
Update docker image with latest master

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#250]
The README describes:

```
To try Python interface directly from CLI, you can run docker image as:

docker run -it --entrypoint=/bin/sh bluebrain/nmodl
```

I am sure the docker image is not up to date with latest master. Can this be done via travis or dockerhub?

**Comment by alkino** [comment]
@alexsavulescu any progress on that?

**Comment by alexsavulescu** [comment]
There was a docker image with NMODL installed. So this is not valid anymore.
