### ISSUE TITLE
Support for building wheel

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#261]
Considering difficulty to build this with commercial compilers (PGI, Intel) and built time issues reported in  #260, it will be great if we could just have wheel for this project.

We already have setup.py for this project. I wonder how much effort it will be to build the wheel for this project.

@ferdonline : when time permit in coming weeks, may be we could evaluate this?

**Comment by pramodk** [comment]
@alexsavulescu : not priority but something to get familiar with this tool and also grab some of the @ferdonline's expertise on this topic.

**Comment by ohm314** [comment]
@cattabiani and I will take a stab at this.

a few things I had in mind:
* Cleanup build system to have only the `setup.py` and the `CMakeLists.txt` for everything building related.
* Building of the code should be done either through `cmake`, or through the `setup.py` depending on whether you’re going the spack way or if you want to create a wheel to install via pypi
* Documentation building should only be done through `setup.py`
testing should be removed from `setup.py` and it should be run only via `CMakeLists.txt` and that should include both the c++ and the pytests

To simplify cmake building from python we will try scikit-build:
https://scikit-build.readthedocs.io/en/latest/

**Comment by pramodk** [comment]
Just a note : in addition to wheel, typically we need to copy binary to [`.data` directory as we do in NEURON](https://github.com/neuronsimulator/nrn/blob/6165d3756dcf49e33d9f7119d57b0cbf14b875e1/setup.py#L104) and [use shim to launch exe](https://github.com/neuronsimulator/nrn/blob/master/share/lib/python/scripts/_binwrapper.py). I wonder if this is not needed as we built static libraries/binaries in NMODL. @ferdonline knows all details of NEURON implementation.

**Comment by pramodk** [comment]
Implemented!
