### ISSUE TITLE
Building freezed after make after 58%

### ISSUE THREAD

**Issue by ziemowit-s** [BlueBrain/nmodl#283]
Following building process from INSTALL.md, after 

`make -j && make install`

The computer freez around 58%. Require restart. 

**My configuration:**
- Ubuntu 16.04
- flex 2.6.0
- cmake 3.5.1
- bison 3.0.4
- jinja2 2.10
- pyyaml 5.3.1
- pytest 5.4.1
- sympy 1.5.1

Python 3.6 with Anaconda environment

**console snippet:**

```
(neuron) ziemek@hall:~/utils/nmodl/build$ cmake .. DCMAKE_INSTALL_PREFIX=$HOME/nmodl
-- CHECKING FOR FLEX/BISON
-- NMODL_FORMATTING: OFF
-- NMODL_FORMATTING_ON: all
-- NMODL_FORMATTING_CPP_CHANGES_ONLY: OFF
-- NMODL_TEST_FORMATTING: OFF
-- NMODL_FORMATTING_NO_SUBMODULES: ON
-- NMODL_CLANG_FORMAT: OFF
-- NMODL_CMAKE_FORMAT: OFF
-- NMODL_PRECOMMIT: OFF
-- NMODL_PRECOMMIT_REGEN: OFF
-- NMODL_STATIC_ANALYSIS: OFF
-- NMODL_TEST_STATIC_ANALYSIS: OFF
-- Could NOT find ClangFormat (missing:  ClangFormat_EXECUTABLE) 
-- CHECKING FOR PYTHON
-- Found PythonInterp: /home/ziemek/anaconda3/envs/neuron/bin/python3.6 (found suitable version "3.6.10", minimum required is "3.6") 
-- INCLUDING PYBIND11
-- Found PythonInterp: /home/ziemek/anaconda3/envs/neuron/bin/python3.6 (found version "3.6.10") 
-- pybind11 v2.3.dev0
-- INCLUDING FMT
-- Version: 6.1.3
-- Build type: 
-- CXX_STANDARD: 11
-- Required features: cxx_variadic_templates
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ziemek/utils/nmodl/build
```

Photo documented making process:

- I couldn't make copy-paste because everything stopped working 

[https://drive.google.com/file/d/1A_58kYSPvTEgri8PDxP0zo5Unyf1ESjY/view?usp=sharing](url)

**Comment by pramodk** [comment]
@ziemowit-s : thank you very much for reporting this and screenshot!

Did you do `make -j` while building? One of the library inside nmodl is quite heavy and takes some time to build. 

I will come back to you with possible suggestions to solve this issue.

**Comment by ziemowit-s** [comment]
Yes, I did `make -j`

**Comment by pramodk** [comment]
@ziemowit-s : could you try following:

```
cmake .. DCMAKE_INSTALL_PREFIX=$HOME/nmodl -DCMAKE_BUILD_TYPE=Debug
make
```

i.e. use `Debug` build type and don't use `-j` (i.e. compile serially).

Some of the Python bindings take significant compilation time. The `make -j` command launch many compilation processes at same time which use quite some resources.

In near future we are going generate Python wheels that will eliminate this issue.

**Comment by ziemowit-s** [comment]
Hi,

Sorry for the delay. After executing the command you profvided I had the same error, at 58%. 

Output files:
  * [CMakeOutput.log](https://gist.github.com/ziemowit-s/5dc0415824e81abb500c22d8b18e07e5)
  * [CMakeError.log](https://gist.github.com/ziemowit-s/2b53fcc9293736eebfc7c4193fe318cf)

**Comment by pramodk** [comment]
@ziemowit-s : we have released now binary wheels. You can do `pip3 install nmodl` to get binary packages.
