### ISSUE TITLE
Ast::set_parent_in_children should not be virtual

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/nmodl#295]
This member function is called in Ast classes constructors exclusively AFAIK. Virtual methods should not be called in constructors, more details in [isocpp.org wiki](https://isocpp.org/wiki/faq/strange-inheritance#calling-virtuals-from-ctors)
I suggest making it a simple private member function in every sub-classes of ast having children.

**Comment by cattabiani** [comment]
I agree. Copy-paste error
