### ISSUE TITLE
Support for INCLUDE construct

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#300]
Currently NMODL doesn't support INCLUDE construct. See an example here: https://github.com/Neurosim-lab/netpyne/blob/coreneuron/examples/coreneuron/m1/mod/MyExp2SynNMDABB.mod

Possible implementations:
* Before starting parsing, do text processing and simply copy the INCLUDEs recursively in the main file (disadvantage: context is lost, I think MOD2C does this?)
* NMODL parser `nmodl.yy` instantiates new NMODL parser when encounter INCLUDE.
* Implement visitor that replaces INCLUDEs with new AST nodes

https://github.com/BlueBrain/CoreNeuron/issues/220

**Comment by tristan0x** [comment]
Command specification can be found [here](https://neuronsimulator.github.io/nrn/py_doc/modelspec/programmatic/mechanisms/nmodl.html#include)

**Comment by tristan0x** [comment]
> Possible implementations:
> 
> * Before starting parsing, do text processing and simply copy the INCLUDEs recursively in the main file (disadvantage: context is lost, I think MOD2C does this?)

Stream performance would be terrible is that case, and as mentioned, not ideal for the user.

> * NMODL parser `nmodl.yy` instantiates new NMODL parser when encounter INCLUDE.

IMO the best option especially when thinking about error reporting. As a user, I would expect a depth-first reporting of errors.

> * Implement visitor that replaces INCLUDEs with new AST nodes

The most non-intrusive solution, but as mentioned above, error reporting is not optimal: if one error occurred in the top file, the _include_ visitor won't be executed and errors in sub-files won't be reported.

**Comment by pramodk** [comment]
> IMO the best option especially when thinking about error reporting. As a user, I would expect a depth-first reporting of errors.

Agree, same preference.  As all of our parsers reentrant (IIRC), instantiating new parser within nmodl parser would be straightforward I think (as done for [VERBATIM statements here](https://github.com/BlueBrain/nmodl/blob/2969adbf3302a58520e6f55dafcb1a4ccdf2df0a/src/parser/nmodl.yy#L479)).

Few additional points:
* we will add/attach sub-AST returned by new parser into main AST. We should still have way to distinguish main program vs included program.
* this is important when convert AST back NMODL. When we do so, we want to produce MOD file with include statement like original one and not everything **after** included. (i.e. `to_nmodl` method should produce original input).
* One way to achieve this could be still have top level node type like **_IncludeNode_** (members can be modified than original string).

**Comment by tristan0x** [comment]
> * One way to achieve this could be still have top level node type like **_IncludeNode_** (members can be modified than original string).

Thank you for telling me this now: I was about to remove the `Include` AST node :)
I will keep it instead, and attach the sub-ast there.

**Comment by tristan0x** [comment]
> Command specification can be found [here](https://neuronsimulator.github.io/nrn/py_doc/modelspec/programmatic/mechanisms/nmodl.html#include)

@pramodk Do you know if the double-quotes in the filename are mandatory i.e is `INCLUDE units.inc` valid?
