### ISSUE TITLE
Issue while running examples from Kinetic scheme Jupyeter notebook

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#307]
If we try run python [examples from this notebook](https://bluebrain.github.io/nmodl/html/notebooks/nmodl-kinetic-schemes.html), we get segfault.
To reproduce the issue, just copy the python example from the notebook and run locally via Python.

I believe this is the main reason for documentation failure in #305.

**Comment by cattabiani** [comment]
I checked and the examples work just fine in py pc

**Comment by ohm314** [comment]
I have verified this and believe that (if not before) it was fixed in #325
