### ISSUE TITLE
Unify nrnunits.lib / upstream any changes from nrnunits.lib

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#317]
When units parser support was added in #145 I think we inherited nrnunits.lib from mod2c and did some changes (?). As we are now integrating NMODL with NEURON, it would be best if they are same.

We should:
* check what is changed between NEURON, MOD2C and NMODL
* make necessary changes so that everything is consistent

**Comment by iomaganaris** [comment]
Currently `NEURON`, `CoreNEURON` and `NMODL` set the same values for units in `nrnunits.lib1` which are the `legacy` ones. When `NEURON` moves to using the latest values, we should also update the values on the `nrnunits.lib` files of `NMODL` and `CoreNEURON` to match the updated values.
See related `NEURON` ticket: https://github.com/neuronsimulator/nrn/issues/521

**Comment by alkino** [comment]
I think, we can close this ticket as we now have legacy / new units in coreneuron / nmodl / mod2c / nrn? @iomaganaris

**Comment by iomaganaris** [comment]
Exactly. This now can be closed
