### ISSUE TITLE
Fix portability issues with wheel on manylinux1 platform

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#319]
As we are targeting NMODL release with NEURON wheel, build the NMODL on manylinux1 platform and address any incompatibilities if any.

**Comment by ohm314** [comment]
As discussed on slack, we should also explore other docker platforms. Specifically scikit-build recommends using dockcross-manylinux 
https://scikit-build.readthedocs.io/en/latest/generators.html?highlight=dockcross-manylinux#linux

The different options should be evaluated for nmodl before a decision is made.

**Comment by pramodk** [comment]
Yes. But note that `dockcross-manylinux` or `multibuild` are services and underlying they uses same `manylinux` platforms.  So portability issues for `the code` needs to be handled independently.

**Comment by mgeplf** [comment]
> Alternatively you mention the manylinux-2010 platform. Can you explain why exactly manylinux1 is needed for nmodl?

I second this: I would really consider doing manylinux2010 - you get the newer compiler, so you don't have to do as many work-arounds, and I'm not sure there are many systems out there that are running python 3.5 (~2015 - a reasonable minimal python version, IMO) that don't have support for manylinux2010 (ie: CentOS 6, [similar to RHEL6, circa 2010/2011)

**Comment by pramodk** [comment]
> I second this: I would really consider doing manylinux2010 - you get the newer compiler, so you don't have to do as many work-arounds,

@mgeplf : I am glad that you looked at this discussion already! Actually, I had so little understanding of `python wheels` and what it means the portability. During last week I started reading about this topic and summarising all references in https://github.com/neuronsimulator/nrn/issues/511. My intent was to understand this topic bit more and then have a discussion with you and @wizmer about this . For example, why you guys still building manylinux1 wheels and choice of C++ standard ([meeting notes](https://bbpteam.epfl.ch/project/spaces/pages/viewpage.action?pageId=51544430)).

> Can you explain why exactly manylinux1 is needed for nmodl?

Now about this : the reason I started I looking at this is that for NEURON we setup manylinux1 wheels in https://github.com/neuronsimulator/nrn/pull/468. I started building coreneuron and NMODL support in NEURON wheel and that's where I created this issue. Note that Neuron+NMODL+CoreNEURON are <=C++11 today so manylinux1 support is "almost free".

**Comment by mgeplf** [comment]
I moved libsonata to manylinux2010:
https://github.com/BlueBrain/libsonata-wheels/blob/master/.travis.yml#L9

I suppose MorphIO switchover hasn't changed yet due to not having time - I have a branch there, and tested it, but I need to update it, and sync it w/ how the deployment in libsonata works for using testing.pypi.org.
