### ISSUE TITLE
NMODL-to-NMODL Optimisations

### ISSUE THREAD

**Issue by thorstenhater** [BlueBrain/nmodl#328]
Dear NMODL team,

I found an interesting comment in your paper and am interested in trying the
feature. Quote from the pre-print

> We have implemented a AST-to-NMODL transformation compiler pass to convert optimized AST > back to the NMODL DSL form. This is not only useful to track the AST transformations during 
> development/debugging but also to generate optimized NMODL DSL that can be consumed by > existing transpilers like nocmodl and mod2c which lack such optimization capabilities.

Do you have an example how this is accomplished?

Best regards.

**Comment by iomaganaris** [comment]
Hello @thorstenhater ,

Thank you for your interest in `NMODL` and its features!
To accomplish this there is a command line option `passes --nmodl-ast` [1] which generates a `NMODL DSL` temporary file after each optimization pass of the `AST`.
For example:
```
./bin/nmodl ../nmodl/ext/example/hh.mod passes --inline --localize --nmodl-ast sympy --analytic
```
This will generate a `tmp` folder where the temporary `mod` files after each pass are saved.
```
➜  ls tmp
hh.0.ast.mod             hh.1.verbatim_rename.mod hh.2.kinetic.mod         hh.3.steadystate.mod     hh.4.inline.mod          hh.5.localize.mod        hh.6.sympy_solve.mod     hh.7.cnexp.mod           hh.8.solveblock.mod
```
Those `mod` files are generated in the code in [main.cpp](https://github.com/BlueBrain/nmodl/blob/master/src/nmodl/main.cpp) where there is a call to `ast_to_nmodl(*ast, filepath("<visitor-name>"));`. You can also see in the same file the various optimization passes running.
In my example I have added the `inline` and `localize` optimazation passes and I use the `sympy --analytic` solver to show an example of the `NMODL` files generated after these optimization passes.
We are also going to add this example to the documentation of `NMODL`.
Please let us know if you have any other question about `NMODL` and we will be happy to help.

Ioannis

[1] https://github.com/BlueBrain/nmodl#high-level-analysis-and-code-generation

**Comment by pramodk** [comment]
@thorstenhater : do you have any other questions about this? Otherwise we can close this ticket.

**Comment by thorstenhater** [comment]
No, thanks a lot!
