### ISSUE TITLE
Use external fmt with spdlog

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#332]
Currently we use fmt as well as spdlog. Spdlog ships it's internal fmt and that causes conflict depending on the include order.  We have to investigate if ~only~ spdlog can be ~used instead~ configured to use external fmt library used with the NMODL. See https://github.com/BlueBrain/nmodl/pull/331#discussion_r425621499.

**Comment by mgeplf** [comment]
> We have to investigate if only spdlog can be used instead.

That was not the intent of my comment: the intent is to use only a single `fmt`, and then have `spdlog` use it, instead of the bundled one.

This way you control the `fmt` version, and you only have no chance of having a mix of them in the library, which will only cause headaches and workarounds.

**Comment by pramodk** [comment]
yeah, agree! I didn't write description correctly (the intent of ticket title was the same :) ).
