### ISSUE TITLE
Broken docs deployment

### ISSUE THREAD

**Issue by cattabiani** [BlueBrain/nmodl#338]
Docs are not deploying anymore since we moved to the new skbuild+sphinx method

**Comment by cattabiani** [comment]
Docs are not deploying anymore since we moved to the new skbuild+sphinx method

**Comment by cattabiani** [comment]
Docs are not deploying anymore since we moved to the new skbuild+sphinx method

**Comment by ohm314** [comment]
Fixed in #325
