### ISSUE TITLE
Cmake-format changes order of code on every PR

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/nmodl#350]
In a lot of PR we have figured out that the following code changes the order it is printed, going up or down the code.
```
set(PYBIND_GENERATED_SOURCES	
    ${PROJECT_BINARY_DIR}/src/pybind/pyast.cpp	
    ${PROJECT_BINARY_DIR}/src/pybind/pyast.hpp	
    ${PROJECT_BINARY_DIR}/src/pybind/pysymtab.cpp	
    ${PROJECT_BINARY_DIR}/src/pybind/pyvisitor.cpp	
    ${PROJECT_BINARY_DIR}/src/pybind/pyvisitor.hpp	
)
```
There is probably some issue with `cmake-format` and some specific which we need to figure out

**Comment by cattabiani** [comment]
+1. I experienced this problem too.

**Comment by tristan0x** [comment]
cmake-format is disabled in this section, I think the issue in somewhere when generating the code:

https://github.com/BlueBrain/nmodl/blob/806e08c68a72d7a503beda8f83dc728fc0e41b60/src/language/templates/code_generator.cmake#L24-L29

It is my understanding that the `| sort(attribute="1")` should ensure a consistent order though.

**Comment by tristan0x** [comment]
Should be `| sort(attribute="0")`!
I will test that fix tomorrow.
