### ISSUE TITLE
Implement PROTECT keyword support 

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#358]
One of the mod file ([ampanmda.mod](https://senselab.med.yale.edu/ModelDB/showmodel.cshtml?model=151681&file=/bulb3d/ampanmda.mod#tabs-2)) from 3D model of the olfactory bulb uses PROTECT keyword as:

```
NEURON {
	POINT_PROCESS AmpaNmda
	RANGE R, g, mg, inmda, iampa, gnmda, gampa
	RANGE x, mgid, ggid, srcgid, gmax
	NONSPECIFIC_CURRENT i
	GLOBAL Cdur, Alpha, Beta, E, Rinf, Rtau, ampatau
	GLOBAL gampafactor, nmdafactor
	GLOBAL ltdinvl, ltpinvl, sighalf, sigslope
}

INITIAL {
	PROTECT Rinf = Alpha / (Alpha + Beta)
	PROTECT Rtau = 1 / (Alpha + Beta)
	synon = 0
	gampa = 0
}
```

These constructs are correctly parsed but we need to support them in code generation.

@nrnhines : Does these variables just become RANGE? (for vectorisation or GPU)

**Comment by nrnhines** [comment]
It is best if one can avoid making them RANGE. One needs only one instance of them for all threads and instances. They are constant during fadvance. The GLOBAL value of Rinf depends only on the GLOBAL value of Alpha and Beta . In a serial program
it does not matter if Rinf is set to the same value thousands of times (once per instance) PROTECT just avoids a possible race when this is done with multiple threads.  Clearly, at the expense of wasted space, it is ok if they are RANGE.

**Comment by alkino** [comment]
https://github.com/BlueBrain/nmodl/pull/961 <= merged
