### ISSUE TITLE
bulb model mod files should be compiled with NMODL (as well as OpenACC backend)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#370]
Mod files can be found in : 

```
/gpfs/bbp.cscs.ch/project/proj16/kumbhar/pramod_scratch/modeldb-bulb3d-sim/sim
```

**Comment by olupton** [comment]
I assume that this is no longer valid, as we have been testing https://github.com/HumanBrainProject/olfactory-bulb-3d with CoreNEURON, including multiple combinations of NMODL/MOD2C/OpenACC/OpenMP target offload.
