### ISSUE TITLE
nrnunits.lib path is hardcoded : std::runtime_error: Could not found nrnunits.lib

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#377]
After installing wheel we get:

```
○ → /Users/kumbhar/Library/Python/3.7/bin//nmodl ~/workarena/repos/bbp/testcorenrn/mod/nacum.mod
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Could not found nrnunits.lib
Abort trap: 6
```

This is because the units library is searched as:

```
/**
 * \brief Path of nrnutils.lib file
 *
 * nrnunits.lib need to be loaded at runtime. Before project is
 * installed it needs to be read from NMODL_PROJECT_SOURCE_DIR and later
 * from CMAKE_INSTALL_PREFIX.
 */
std::vector<std::string> nmodl::NrnUnitsLib::NRNUNITSLIB_PATH =
    {"@CMAKE_INSTALL_PREFIX@/share/nrnunits.lib", "@NMODL_PROJECT_SOURCE_DIR@/share/nrnunits.lib"};
~
```

So this works on the machine where binary is built but not on other machine!

**Comment by cattabiani** [comment]
from what I understand in the comment, NMODL_PROJECT_SOURCE_DIR is fine (used while building). I do not understand why we use CMAKE_INSTALL_PREFIX to get the location at runtime. Do you think it would be a good idea to add this discovery to the shim with NMODL_PYLIB and NMODL_PYWRAPPER?
