### ISSUE TITLE
nmodl::parser::location class is defined more than once

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/nmodl#380]
I wanted to extend the _format_ library to deal with `nmodl::parser::location` as instructed [here](https://fmt.dev/latest/api.html#formatting-user-defined-types) but realized that every bison parser in NMODL has its owned `location.hh` file:
* `${CMAKE_BINARY_DIR}/src/parser/diffeq/location.hh`
* `${CMAKE_BINARY_DIR}/src/parser/nmodl/location.hh`
* `${CMAKE_BINARY_DIR}/src/parser/unit/location.hh`

Each of them defines a `location` class, all in the same `nmodl::parser` namespace. There should be either one single `nmodl::parser::location` class used by all parsers or they should all be declared in a dedicated namespace. This is an issue that should be addressed before considering extending the _format_ to deal with `nmodl::parser::location`.

_Originally posted by @tristan0x in https://github.com/BlueBrain/nmodl/pull/372#discussion_r463422929_

**Comment by pramodk** [comment]
@tristan0x : I had trouble with this as well! Last time I checked this (~18 months ago) and it was not possible to share location.hh from different parsers. I would be curious to know if you have / find any elegant solution.
