### ISSUE TITLE
`create_statement` should not return a shared pointer, but a Statement

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/nmodl#39]
Logically it doesn't seem to make sense for a helper function like create_statement to do any memory management. Instead a Statement should be returned by copy (and the compiler will elide this copy).

**Comment by tapaswenipathak** [comment]
Can I work on this ticket?

**Comment by pramodk** [comment]
> I understand that @pramodk find it more convenient that create_statement returns a std::shared_ptr

What's your opinion on this @alkino ? I have no preference - if you think its "ok" as it is, lets close the issue. If you think this is "bad", see if it's easy to change.
