### ISSUE TITLE
Implement support for FOR_NETCON using CoreNEURON data structures

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#390]
See corresponding change in MOD2C here : https://github.com/BlueBrain/mod2c/pull/43

**Comment by cattabiani** [comment]
right now, for_netcons is not even producing working code from nmodl. It compiles to a cpp file but the syntax is not correct. I get this error:

```
error: expected ‘;’ before ‘fnpreftprefnpostftpost’
  245 |                 (*w)fnpreftprefnpostftpost{
```
