### ISSUE TITLE
Delay connections + NMODL = error: 'net_send_buffering' not declared

### ISSUE THREAD

**Issue by cattabiani** [BlueBrain/nmodl#404]
Hello all!

This problem is related with the delayed connections implemented by @ohm314 . It changed the common mod files in neocortex. For example, with DetAMPANMDA, while compiling with coreneuron+nmodl I get this error:

```
DetAMPANMDA.cpp:433:13: error: ‘net_send_buffering’ was not declared in this scope
net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[4*pnodecount+id], -1, inst->point_process[1*pnodecount+id], nt->_t+next_delay_t, 1.0);
```

**Comment by iomaganaris** [comment]
Fixed in https://github.com/BlueBrain/nmodl/pull/405
