### ISSUE TITLE
nmodl needs same units configuration flexibility as mod2c

### ISSUE THREAD

**Issue by nrnhines** [BlueBrain/nmodl#416]
nmodl should have the same configuration flexibility (not dynamic) for unit selection as the current configuration flexibility
of mod2c (see BlueBrain/mod2c#53).
I believe this would close all issues in coreneuron and nmodl that involve units.

**Comment by pramodk** [comment]
@alkino : only relevant change in mod2c from https://github.com/BlueBrain/mod2c/pull/53/ is :

```
#if USE_LEGACY_UNITS
   sprintf(buf, "\ndouble %s = %g;\n", name, u);
 #else
   /* compiler can't read %a format til c++17 (or c99) */
   sprintf(buf, "\ndouble %s = /* %a; */ %.18g;\n", name, u, u);
 #endif
```

So we have to do something similar in NMODL based on legacy units on or off. I am not sure (yet) where unit values are printed in NMODL but wondering if it's in : https://github.com/BlueBrain/nmodl/blob/fee633581c206f9c137c5e2eca2d053e7c761d11/src/codegen/codegen_c_visitor.cpp#L2968 

(@iomaganaris can help here)

**Comment by pramodk** [comment]
@alkino : note that this is an old issue and could be addressed now.
