### ISSUE TITLE
Automated wheel building

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#417]
Similar to NEURON, we should build the wheel for NMODL in automated way. Here [are instructions from NEURON](https://github.com/neuronsimulator/nrn/tree/master/packaging/python).

Here are steps:

* Adapt Dockerfile for NMODL (if we are using C++14 and if GCC 4.8.5 is not sufficient, we might need to use Manylinux2010)
* This is how docker image is launched to build for linux : [Pipeline](https://github.com/neuronsimulator/nrn/blob/cccff1461ebf15dd6686ff966ae9dd9f7cc0775a/azure-pipelines.yml#L39)
* Update wheel [building script](https://github.com/neuronsimulator/nrn/blob/master/packaging/python/build_wheels.bash)
* Create [test script](https://github.com/neuronsimulator/nrn/blob/master/packaging/python/test_wheels.sh) for NMODL

cc: @ohm314

**Comment by ohm314** [comment]
We use C++14 for now, so on that front we're safe
