### ISSUE TITLE
Make sure code generation falls back from ISPC to C++ when Eigen solver is needed

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/nmodl#418]
Currently the Eigen solver is used with the `sympy` mode for `derivimplicit` and `sparse` `SOLVE` methods. But the solver cannot be used in combination with ISPC code generation. In these cases, nmodl should fall back to generating C++ instead.

**Comment by cattabiani** [comment]
right now, does it raise an error or it produces wrong code?

**Comment by ohm314** [comment]
special trick.. I went into the past and fixed this: https://github.com/BlueBrain/nmodl/commit/b8fc1301a3b4fef1a37b7d4b678779fb5af4d8a9
that's how good i am...
