### ISSUE TITLE
"in" variable in mod files break ispc compilation (reserved keyword)

### ISSUE THREAD

**Issue by cattabiani** [BlueBrain/nmodl#424]
In ican.mod (thalamus) there is this:

> USEION n READ en WRITE **in** VALENCE 1

Unfortunately, **in** is a reserved keyword for ispc:

> The following identifiers are reserved as language keywords: bool, break, case, cdo, cfor, char, cif, cwhile, const, continue, default, do, double, else, enum, export, extern, false, float, for, foreach, foreach_active, foreach_tiled, foreach_unique, goto, if, **in**, inline, noinline, __vectorcall, int, int8, int16, int32, int64, launch, NULL, print, return, signed, sizeof, soa, static, struct, switch, sync, task, true, typedef, uniform, union, unsigned, varying, void, volatile, while.

The problem with just renaming in the ispc code is that in the hoc/python file we should be able to do something like:

`a = soma(0.5)._ref_in`

maybe I am missing something but I do not think that this would work if we rename the variable for ispc...

**Comment by pramodk** [comment]
With ion name `x`, the variable names like `ex`, `ix` have special meaning and hence renaming won't be possible in this specific case.

One possible option is to fallback to C++ code generator if ISPC code generation is not possible. We have a method in ISPC codegen visitor that checks if MOD file is compatible for ISPC or not.

**Comment by cattabiani** [comment]
I checked and in ispc the variable appears only in:

```
/** all mechanism instance variables */
struct ican_Instance  {
    const double* uniform gbar;
    double* uniform in;
```
