### ISSUE TITLE
Wrong order of ion variables declaration in mod file

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/nmodl#436]
When compiling `cal_mig.mod` from https://github.com/Neurosim-lab/netpyne/blob/coreneuron/examples/coreneuron/m1/mod/cal_mig.mod the order of the `cai` and `ica` `ion` channels' variables is wrong in the generated `.cpp` file by `NMODL`.
The issue is fixed if `cai` and `ica` definition as `RANGE` variables in `line 44` is removed.
We need to check again the order of the printing of the `ion` variables in `NMODL` to make sure it's the same as `neuron nmodl`.

**Comment by cattabiani** [comment]
I can take a look. How much priority this has?

**Comment by pramodk** [comment]
@cattabiani : me and Ioannis were debugging this issue yesterday. I am already looking at this (will create PR after double/float as a string PR is done).

**Comment by cattabiani** [comment]
I did not see the last comment
