### ISSUE TITLE
Update pybind to support python >= 3.10

### ISSUE THREAD

**Issue by alkino** [BlueBrain/nmodl#445]
From python 3.10, backward compatibility with 2.7 will be remove. (https://docs.python.org/3/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code)

We should update pybind11 to 2.6.0 at least, but it requires cmake 3.4 and cmake is currently 3.3 at least in nmodl.

We should take time to update pybind11 and change the minimum version required of cmake.

For remembering it is 3.7 in coreneuron and neuron

**Comment by pramodk** [comment]
As mentioned on Slack, updating to 3.4 (or ~3.8-3.9) is not a problem at all.
