### ISSUE TITLE
nightly wheels fail to upload

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/nmodl#448]
There is still a small issue in the nightly wheel building. it seems that the nightly tag is not properly set and so the built packages, while valid don't have the correct name to be uploaded:
The issue is most likely here:
https://github.com/BlueBrain/nmodl/blob/6c85112faa07e5a7dba252715534eb4d1051960f/azure-pipelines.yml#L147
and here:
https://github.com/BlueBrain/nmodl/blob/6c85112faa07e5a7dba252715534eb4d1051960f/azure-pipelines.yml#L207

**Comment by pramodk** [comment]
@ohm314 : I thought this was fixed with your last changes.

**Comment by cattabiani** [comment]
just a naiive question (probably): shouldn't it be

```
${buildWheel}==true
```
