### ISSUE TITLE
Redesign symbol table in LLVM visitor

### ISSUE THREAD

**Issue by georgemitenkov** [BlueBrain/nmodl#469]
Currently, a map `name -> llvm::Value*` is used for named variables. This is limited to local function scope. We need to:
- Support function name to block mappings
- Support local and global variable lookups (Some inspiration can be taken from LLVM's implementation of `SymbolTable`)

**Comment by pramodk** [comment]
Just FYI as a reference: 

* for DSL, symbol table implementation is here: https://github.com/BlueBrain/nmodl/blob/master/src/symtab/symbol_table.hpp
* You can see tests in : https://github.com/BlueBrain/nmodl/blob/master/test/unit/symtab/symbol_table.cpp

We can make existing implementation generic (type agnostic) if that is helpful. But I assume you may not needed anything too advanced?

Anyway, if you need any help / information, let me know.

**Comment by georgemitenkov** [comment]
Thanks! I will have a look at these.
