### ISSUE TITLE
' parsed as operator

### ISSUE THREAD

**Issue by cattabiani** [BlueBrain/nmodl#511]
for this [PR](https://github.com/BlueBrain/nmodl/pull/495) I need to get the variable of a derivative. For example:

```
a' -> a
F'[0] -> F[0]
```

Right now, the ' is embedded in the definition of the name node. Name vs PrimeName. In addition, this means that we can have only 1st derivatives of a variable (in case we want to expand the language). 

It would be nice to have it as an operator instead so that we can convert from derivative to variable simply erasing that node.

**Comment by WeinaJi** [comment]
https://github.com/BlueBrain/nmodl/blob/d7b82bb1fae0fdc6b9e8da6908731af447e5e659/src/lexer/nmodl_utils.cpp#L93-L103
Looking at the ``prime_symbol``constructor, it seems that it counts the number of ``'`` as the prime order. Is the order attribute used in the solver ? @iomaganaris @cattabiani

**Comment by iomaganaris** [comment]
I took a brief look and I thought of these two options:

Proposal 1 (fairly easy but bit dirty):

- `get_node_with_index() { return node.get_node_name() << "[" << to_nmodl(node.get_length()) << "]"; }` in IndexedName.cpp
- Create utility function that check whether there is just a simple `Name` or `IndexedName` and returns the proper string
- Use this function in https://github.com/BlueBrain/nmodl/blob/07c7267998e2066f744885e43b88a595aa5f5591/src/visitors/visitor_utils.cpp#L249

Proposal 2 (more complex, adds more information in `VarName`):

- Create new rule in https://github.com/BlueBrain/nmodl/blob/d28f0bee20bc55ccda9ba9371f2118127138100d/src/lexer/nmodl.ll#L111 for prime symbols and name symbols (i.e. `prime_name`)
- Distinguish operator `'` or multiple `'`s when creating `prime_name`
- Add `derivative` member in `VarName` type that takes the operator (and the order of the derivative)
- Add rule for `prime_name` in https://github.com/BlueBrain/nmodl/blob/d28f0bee20bc55ccda9ba9371f2118127138100d/src/parser/nmodl.yy#L1251 `variable_name` that creates `VarName` with derivative
- Still need of utility function or a common function between `IndexedName` and `Name` to get the full string of the `VarName` (either just `a` or `F[0]`)
- Check whether this can be used in other places or if it breaks anything

@pramodk @WeinaJi what do you think?

**Comment by cattabiani** [comment]
> key = to_nmodl(lhs); 
this function, as it is right now, does not solve the problem because it returns with the prime

**Comment by iomaganaris** [comment]
> > key = to_nmodl(lhs);
> 
> this function, as it is right now, does not solve the problem because it returns with the prime

Yes, sorry, I updated my previous comment. I meant use `get_nodee_with_index()` instead of `to_nmodl(lhs)` and then removing `'`

**Comment by cattabiani** [comment]
I think this was my workaround

**Comment by iomaganaris** [comment]
It's a similar solution but it would be part of `IndexedName` class

**Comment by WeinaJi** [comment]
Hello @iomaganaris @cattabiani , thanks for the proposals. Proposal 1 seems to be easier for me to start with. 
Is there already a unit test to test the `IndexedName` ?

**Comment by iomaganaris** [comment]
I don't think there is a unit test for `IndexedName`. To test the class you can do simply something like this https://github.com/BlueBrain/nmodl/commit/c0c34b57fa1a367dc64c0db731c7495aa61cf3e9. Since `IndexedName` class' code is automatically generated with `jinja` to enrich the class it's needed to edit https://github.com/BlueBrain/nmodl/blob/master/src/language/templates/ast/node_class.template and https://github.com/BlueBrain/nmodl/blob/master/src/language/nodes.py. We can discuss more about this on a call tomorrow if you want on how the `ast` classes are automatically generated
