### ISSUE TITLE
`sympy_visitor` clash of variables of type `tmp*` and `old_*` with the user-defined ones

### ISSUE THREAD

**Issue by cattabiani** [BlueBrain/nmodl#515]
`sympy_visitor` creates some variables of type `tmp*` and `old_*`. Clashes with user-defined variables are not checked. This could lead to bugs (probably compilation errors)

It was already marked as `TODO` in the code. Now we also have an issue

**Comment by iomaganaris** [comment]
FYI there is a `suffix_random_string()` function in `NMODL utils` that generates a unique variable name for these cases. This is used in the `RenameVisitor` and the `sympy_solver_visitor`

**Comment by cattabiani** [comment]
I noticed it is already used for F vector and J matrix (I guess because there there is the obvious clash with the Faraday constant). However, @pramodk suggested that, to keep it simple, we can also prepend a `_` since nmodl does not accepts already variables starting with that char
