### ISSUE TITLE
remove scikit from setup.py

### ISSUE THREAD

**Issue by cattabiani** [BlueBrain/nmodl#557]
scikit drawbacks:

- it does a lot of magic
- not very well documented
- poor support from maintainers
- outsourcing to scikit magic requires to dig inside their code when things do not work
- everything is clearer if it is confined to our setup.py

Thus, the consensus is that setup.py should be rewritten so that we do not use scikit; we call cmake ourself and move stuff around

**Comment by pramodk** [comment]
@alkino : I am un-assigning this from your queue for time being. IIRC, there were some subtleties. So we should have a brief discussion before tackling this issue.
