### ISSUE TITLE
Remove support for AoS layout from NMODL

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#563]
NMODL currently has support for AoS layout. This was added for compatibility and testing with MOD2C and CoreNEURON.
I think we should remove AoS support due to following reasons:

* In practice, we never use AoS layout for CPU vectorisation or GPUs
* This part remains untested because of the same reason
* The code generation code could become simple and streamlined

But what if we need this for NEURON or some other purpose?

* The changes are only at the final level i.e. code generation stage 
* NEURON will have different code generation printing class. So there we could easily add AoS related logic

What needs to be done as part of this Issue?

* Remove CLI option in nmodl for layout 
* Remove all logic in src/codegen where we we are using `LayoutType::aos`. Simplify code assuming `LayoutType::soma` is default.

**Comment by pramodk** [comment]
@nrnhines : Practically, I think we should just keep SoA related code in CoreNEURON + NMODL. what do you think about this?

**Comment by nrnhines** [comment]
I have no issue with that. It seems possible now to have SoA in NEURON. I don't understand why uniform replacement of every NEURON RANGE variable by ```typedef std::vector<double> NrnRangeVariable``` wouldn't be straightforward.  (Except for the details of nseg change, section removal/addition, mechanism insertion/deletion into a section, point process moving, creation, destruction, nthread change, permutation for high performance.:)
