### ISSUE TITLE
Enable sympy solver when there is a sparse method used

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/nmodl#577]
Whenever there is a `sparse` solve method defined in a mod file
```
SOLVE <kinetic> METHOD sparse
```
and `sympy` solver is not defined from the CLI arguments passed the `NeuronSolveVisitor` fails with
```
[NMODL] [error] :: NeuronSolveVisitor :: solver method 'sparse' not supported
```
Instead we should check if there is a `sparse` solver used in the mod file and enable automatically the `sympy --analytic` pass to use this solver.
A message/warning should also be printed in the output to let the user know that `sympy` was enabled.

**Comment by alkino** [comment]
from @pramodk 
```i.e. if sympy is not enabled on CLI and we see that sparse solver is used then we show warning message and enable sympy based solvers automatically. (this will be change in just main.cpp of NMODL) (edited) 
simply we need to check if KINETIC block exist or SOLVE method is sparse. So with simple helper function (in main.cpp or visitor_utils), this could be achieved?
Because it's more or less, is_sympy_solver_required() which will check existence of sparse method or KINETIC block.```
