### ISSUE TITLE
Add option to build without python

### ISSUE THREAD

**Issue by lkeegan** [BlueBrain/nmodl#6]
Would be good to have a CMake option to build NMODL without any python dependencies

**Comment by alkino** [comment]
@pramodk can we close this with https://github.com/BlueBrain/nmodl/pull/428

**Comment by pramodk** [comment]
This ticket was to avoid use of Python libraries completely i.e. even no sympy usage in solvers.

Today NMODL is distributed as wheel and easy to install for end users. Also, with #428 build from source is reasonably faster. So I think we can close this ticket.
