### ISSUE TITLE
Change CoreNEURON testing under Azure CI

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#608]
Currently we are running integration test by installing CoreNEURON, see https://github.com/BlueBrain/nmodl/blob/dcaf303566bf4a183cf667e31a45a680c7a006fe/azure-pipelines.yml#L71

Above test only runs basic ring test inside CoreNEURON. With the work done in https://github.com/BlueBrain/CoreNeuron/issues/522, we should use NEURON to run all tests with NMODL i.e.
* clone neuron
* enable coreneuron, nmodl, test
* run all tests

This will make sure we are testing good amount of integration tests under CI.

**Comment by alkino** [comment]
Should we stop using CoreNeuron tests? are they a subset of neuron tests?

Or run Neuron + CoreNeuron tests?

**Comment by pramodk** [comment]
They are smaller subset of NEURON. So we remove existing CoreNEURON test and enable NEURON+CoreNEURON tests (with Cmake option for enabling test)

**Comment by alkino** [comment]
Close by #610
