### ISSUE TITLE
Dumping LLVM JIT module to assembly

### ISSUE THREAD

**Issue by georgemitenkov** [BlueBrain/nmodl#611]
Currently, we not see the assembly generated from LLVM IR module when passing it to JIT. We need to find a way (see #592) to verify that the instructions are produced for intended platforms.

**Comment by georgemitenkov** [comment]
Approach 1: Dump to object file and the disassemble
```c++
// add line
jit->getObjTransformLayer().setTransform(llvm::orc::DumpObjects("dir", "name"));
```
then
```bash
$ objdump -D test.o
```

Approach 2:
- [] TODO

**Comment by pramodk** [comment]
`Approach 1` mentioned is already helpful! Based on the API mentioned, I was looking at [the example llvm/examples/OrcV2Examples/LLJITDumpObjects/LLJITDumpObjects.cpp](https://github.com/llvm/llvm-project/blob/main/llvm/examples/OrcV2Examples/LLJITDumpObjects/LLJITDumpObjects.cpp).

**Comment by georgemitenkov** [comment]
Yes, I was looking at the same example!
