### ISSUE TITLE
Adding debug symbols and metadata for profiling kernels

### ISSUE THREAD

**Issue by georgemitenkov** [BlueBrain/nmodl#612]
Issue: #592

We want to have some debug symbols that would allow us to profile the LLVM IR kernels. Consider adding these.

**Comment by pramodk** [comment]
Just a minor note: for #548, we need to add comment/annotation to the loop body:

```asm
$ → cat hh.1.s
....
# LLVM-MCA-BEGIN Body
LBB0_2:                                 ## %for.body
                                        ## =>This Inner Loop Header: Depth=1
	movq	%rsp, %rax
	addq	$-16, %rax
	movq	%rax, %rsp
	movq	%rsp, %rax
	addq	$-16, %rax
	movq	%rax, %rsp
	movq	-16(%rbp), %rax
	movslq	-4(%rbp), %rcx
	movq	(%rax), %rdx
	movq	8(%rax), %rsi
	movq	16(%rax), %rax
	vmovsd	(%rdx,%rcx,8), %xmm0            ## xmm0 = mem[0],zero
	vsubsd	(%rax,%rcx,8), %xmm0, %xmm0
	vdivsd	(%rsi,%rcx,8), %xmm0, %xmm0
	vmovsd	%xmm0, (%rax,%rcx,8)
	incl	-4(%rbp)
	movq	-16(%rbp), %rax
	movl	-4(%rbp), %ecx
	cmpl	92(%rax), %ecx
	jl	LBB0_2
# LLVM-MCA-END
```

In case this is minor/easy to do with few lines. Otherwise don't worry for now.

**Comment by georgemitenkov** [comment]
Do you mean annotation that it is a loop? In this case, I have actually made a ticket for that yesterday: #607. (Also: #606). In LLVM there is `llvm.loop` metadata that Clang emits, so that on I we know that the basic blocks are from the loop 👍 

Or you mean debug symbols/metadata in general for profiling?

**Comment by pramodk** [comment]
May be I shouldn't have mixed the topic in this ticket. Let's get `debug symbols/metadata in general for profiling` for JIT kernels, as we discussed. I will add separate ticket regarding my comment above (this is very minor/low priority thing)
