### ISSUE TITLE
Enable NMODL as part of CoreNEURON CI

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#632]
(this ticket can be in coreneuron project but creating here as we have code generation related [project in this repo](https://github.com/BlueBrain/nmodl/projects/6))

One of the important goal is to replace MOD2C with NMODL inside CoreNEURON. In order to do this, we should make sure all existing tests pass when NMODL is used instead of MOD2C.

**Which tests should be executed?**

When NEURON is built with CoreNEURON and using option `-DNRN_ENABLE_TESTS=ON` then number of tests are executed on CPU as well as GPU. These tests are currently executed as part of CoreNEURON CI on Gitlab.

**What should be done?**

We should add **additional** CI job inside Gitlab that will configure neuron+coreneuron+nmodl and execute tests on CPU as well as GPU. All tests should pass with NMODL (like MOD2C).

**Comment by pramodk** [comment]
There was old PR : https://github.com/BlueBrain/CoreNeuron/pull/523

But 1) it was failing 2) it was replacing existing MOD2C based tests (instead of adding new one).

**Comment by olupton** [comment]
See also: https://github.com/BlueBrain/CoreNeuron/issues/522

**Comment by cattabiani** [comment]
could this be done with cvf? I never tried to run on gpu

**Comment by pramodk** [comment]
@alkino : this is addressed now?

**Comment by alkino** [comment]
Partly, we still have to take care of: https://github.com/neuronsimulator/nrn/pull/1338#issuecomment-867384405
to be fully compliant

**Comment by olupton** [comment]
https://github.com/neuronsimulator/nrn/pull/1377 addressed those TODOs, so I think we can close this now.
