### ISSUE TITLE
Add parent pointer into AST nodes

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/nmodl#65]
As a first step to simplifying some of the AST operations I think it would be useful to give each AST node a parent member, which is a pointer to an AST node (its parent or nullptr). This should be a shared_ptr and the pointer shoudl be set trhough a `set_parent()` method when the child is added into its parent (e.g. when the child is passed to the parent in the constructor or in one of the `add_statement` / `update` methods.

**Comment by tapaswenipathak** [comment]
hello @ohm314, this is interesting, can I PR for this?
