### ISSUE TITLE
Sympy analytic solver is incompatible with GPU execution.

### ISSUE THREAD

**Issue by olupton** [BlueBrain/nmodl#725]
The `sympy --analytic` option to NMODL produces code that crashes on GPU.
The same models pass on GPU if this option is not passed.
This option is enabled by the `+sympy` variant of the CoreNEURON Spack recipe.

## Reproducing
One way is to use the `channel-benchmark` tests as added in https://github.com/neuronsimulator/nrn/pull/1439.
```
-DNRN_ENABLE_CORENEURON=ON \
-DCORENRN_ENABLE_GPU=ON \
-DCORENRN_ENABLE_NMODL=ON \
-DCORENRN_NMODL_FLAGS=" sympy --analytic"
```
and build (with NVHPC compilers etc.). Two (three, counting the results comparison) tests should fail:
`channel_benchmark_Hippo::coreneuron_gpu` and `channel_benchmark_Hippo::coreneuron_gpu_offline`.

**Comment by pramodk** [comment]
fixed by #728
