### ISSUE TITLE
sympy 1.9 incompatibility with test: Solve ODEs with cnexp or euler method using SympySolverVisitor

### ISSUE THREAD

**Issue by olupton** [BlueBrain/nmodl#749]
[sympy 1.9 was released 2 days ago](https://pypi.org/project/sympy/1.9/), which has caused [CI failures](https://github.com/BlueBrain/nmodl/runs/3856512273):
```
../test/unit/visitor/sympy_solver.cpp:566: FAILED:
  REQUIRE( result[0] == "z' = a/z+b/z/z" )
with expansion:
  "z = (0.5*pow(a, 2)*pow(z, 2)-a*b*z+pow(b, 2)*log(a*z+b))/pow(a, 3)"
  ==
  "z' = a/z+b/z/z"
```

https://github.com/BlueBrain/nmodl/pull/748 stops the new sympy version from being used in the CI, but the underlying issue should be fixed so that we can remove these constraints.

**Comment by cattabiani** [comment]
omg I did not see this being assigned to me for a very long time lol

There are a few ways to tackle this. I will find one
