### ISSUE TITLE
Regression testing of NMODL against ModelDB mod files

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#760]
As part of upcoming release of NEURON for frontiers, we would like to release a stable NMODL version. For this, we should check if NMODL is able to compile all mod files that are compilable by MOD2C. In order to do this we should fo following:

* Build 1) CoreNEURON with MOD2C 2) CoreNEURON with NMODL
* Clone mod files repository
```console
git clone ssh://bbpcode.epfl.ch/hpc/nmodldb -b sandbox/savulesc/downloader
```
which has ~750 models:

![image](https://user-images.githubusercontent.com/666852/138703154-edf46417-3cec-4481-997f-90949dca3443.png)

* Each directory under `nmodldb/models/db/modeldb` has folder `mod`. We should do:

```python
         for each model_dir in nmodldb/models/db/modeldb:
                 # try to compile with mod2c first
                 coreneuron-mod2c-install/bin/nrnivmodl-core model_dir/mod

                if above_is_successful:
                      # try to compile with nmodl
                     coreneuron-nmodl-install/bin/nrnivmodl-core model_dir/mod

                     if above_ails:
                         record model number and store console log
```

Once we have the report then we should go through the failing models and look at what is missing on NMODL side.

* Prepare a simple script so that above process of compiling mod files and checking failing models can be automated.
* Note that at least for parser we have status stored in https://github.com/BlueBrain/nmodl/blob/master/docs/test_status.txt

**Comment by alkino** [comment]
I'm currently running

```
set -e
set -x

module load unstable cmake ninja hpe-mpi gcc bison flex
git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/BlueBrain/CoreNeuron
git clone --depth 1 ssh://bbpcode.epfl.ch/hpc/nmodldb -b sandbox/savulesc/downloader

pushd CoreNeuron
rm -rf BUILD_MOD2C && mkdir BUILD_MOD2C
pushd BUILD_MOD2C
cmake -DCMAKE_GENERATOR=Ninja .. && ninja
popd
rm -rf BUILD_NMODL && mkdir BUILD_NMODL
pushd BUILD_NMODL
cmake -DCMAKE_GENERATOR=Ninja -DCORENRN_ENABLE_NMODL=ON .. && ninja
popd
popd

for i in $(find nmodldb -type d -name mod);
do
  ./CoreNeuron/BUILD_MOD2C/bin/nrnivmodl-core $i > /dev/null 2>&1 && echo $i >> work
  rm -rf x86_64
done

mkdir logs
for i in $(cat work);
do
  ./CoreNeuron/BUILD_NMODL/bin/nrnivmodl-core $i > tmp 2>&1 || mv tmp logs/$i.log
  rm -rf x86_64
done
```

**Comment by pramodk** [comment]
@alkino : About below error

> get_node_name() not implemented:
> ./127507/mod
> ./46839/mod
> ./183424/mod

I tested this issue with your mod file from : `cornu/TEST/nmodldb/./models/db/modeldb/127507/mod/stim.mod`
The MOD file has:
```
	at_time(del)
	at_time(del+dur)
```
and if you run nmodl via gdb then you can see it fails in `codegen_c_visitor.cpp:1417` at `print_function_call()`:
```
       } else if (nmodl::details::needs_neuron_thread_first_arg(function_name) &&
                  arguments.front()->get_node_name() != "nt") {
```
here we call `arguments.front()->get_node_name()`.
When we have argument `del+dur`, this is a binary expression (_and not normal variable type node_) which is wrapped inside another node type `WrappedExpression`. Hence we try to call `get_node_name()` then it fails. Note than `get_node_name()` can not be called on the binary expression and hence error.

In this case we can check the `arguments.front()` node type and then only call / avoid calling `get_node_name()`.

**Comment by pramodk** [comment]
> RANGE and not GLOBAL:

For this, today we consider that user should fix the mod file. It's documented in https://nrn.readthedocs.io/en/latest/coreneuron/compatibility.html#thread-safe-mod-files

> Global local variables (should add passes --local-to-range):

This is something worth discussing. We can do it today @ 2PM dev discussion. It would be great if you could add a slide with 1) example of MOD file 2) how mod2c generate code for this and what is problem 3) how it's done in NMODL

**Comment by alkino** [comment]
All issues are fixed, except one I still didn't discover
