### ISSUE TITLE
clang-tidy compliance should be tested in the CI

### ISSUE THREAD

**Issue by olupton** [BlueBrain/nmodl#910]
https://github.com/BlueBrain/nmodl/pull/902 defines a set of clang-tidy rules and fixes/suppresses the code so that they all pass, but this is not yet enforced in the CI.

When using tools like this, we should add checks to prevent regressions. Unfortunately for clang-tidy this may be a little too slow, but we can investigate. Tools like https://github.com/matus-chochlik/ctcache may be useful.

**Comment by 1uc** [comment]
sonar source will have to suffice.
