### ISSUE TITLE
Implement INDEPENDENT block

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/nmodl#951]
Check the `INDEPENDENT` block implementation and documentation in `NEURON` and add related unit test in `NMODL`. Check also `SWEEP` keyword implementation.

**Comment by iomaganaris** [comment]
`INDEPENDENT` block should only be used with variable `t` in NEURON. If there is another variable set we should print a warning. Also `SWEEP` doesn't matter and no additional code should be generated for `INDEPENDENT` by NMODL

**Comment by alkino** [comment]
Closed by #966
