### ISSUE TITLE
Increase code coverage of CodegenCVisitor

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/nmodl#957]
Currently the code coverage of the https://github.com/BlueBrain/nmodl/blob/master/src/codegen/codegen_cpp_visitor.cpp responsible for printing almost all of the C++ code is around ~89% according to the code coverage report you can find attached.
[nmodl_coverage.zip](https://github.com/BlueBrain/nmodl/files/9728180/nmodl_coverage.zip)
The code coverage was generated using the following script https://github.com/BlueBrain/nmodl/blob/magkanar/codecov/codecov.sh.
This issue is about trying to increase it as much as possible to 100% with the addition of unit or integration tests.

**Comment by iomaganaris** [comment]
Similarly to the `CodegenCVisitor` we should increase the coverage of `CodegenAccVisitor` and the other visitors for the code generation with meaningful tests

**Comment by alkino** [comment]
I did CodegenCompatibilityVisitor here: https://github.com/ModelDBRepository/258643/pull/1
